// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

/*
Package node is a generated protocol buffer package.

It is generated from these files:
	node.proto

It has these top-level messages:
	Info
	StatusParams
	SyncParams
	Block
	PushReturn
*/
package node

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Info struct {
	Version         string `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
	Valid           bool   `protobuf:"varint,2,opt,name=Valid" json:"Valid,omitempty"`
	Length          uint64 `protobuf:"varint,3,opt,name=Length" json:"Length,omitempty"`
	LastHash        []byte `protobuf:"bytes,4,opt,name=LastHash,proto3" json:"LastHash,omitempty"`
	ListenInterface string `protobuf:"bytes,5,opt,name=ListenInterface" json:"ListenInterface,omitempty"`
}

func (m *Info) Reset()                    { *m = Info{} }
func (m *Info) String() string            { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()               {}
func (*Info) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Info) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Info) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Info) GetLength() uint64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Info) GetLastHash() []byte {
	if m != nil {
		return m.LastHash
	}
	return nil
}

func (m *Info) GetListenInterface() string {
	if m != nil {
		return m.ListenInterface
	}
	return ""
}

type StatusParams struct {
	Host string `protobuf:"bytes,1,opt,name=Host" json:"Host,omitempty"`
}

func (m *StatusParams) Reset()                    { *m = StatusParams{} }
func (m *StatusParams) String() string            { return proto.CompactTextString(m) }
func (*StatusParams) ProtoMessage()               {}
func (*StatusParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StatusParams) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type SyncParams struct {
	LastHash []byte `protobuf:"bytes,1,opt,name=LastHash,proto3" json:"LastHash,omitempty"`
}

func (m *SyncParams) Reset()                    { *m = SyncParams{} }
func (m *SyncParams) String() string            { return proto.CompactTextString(m) }
func (*SyncParams) ProtoMessage()               {}
func (*SyncParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SyncParams) GetLastHash() []byte {
	if m != nil {
		return m.LastHash
	}
	return nil
}

type Block struct {
	Content   string `protobuf:"bytes,1,opt,name=Content" json:"Content,omitempty"`
	Nonce     uint32 `protobuf:"varint,2,opt,name=Nonce" json:"Nonce,omitempty"`
	Previous  []byte `protobuf:"bytes,3,opt,name=Previous,proto3" json:"Previous,omitempty"`
	Type      string `protobuf:"bytes,5,opt,name=Type" json:"Type,omitempty"`
	PubKey    string `protobuf:"bytes,6,opt,name=PubKey" json:"PubKey,omitempty"`
	Date      int64  `protobuf:"varint,7,opt,name=Date" json:"Date,omitempty"`
	Signature string `protobuf:"bytes,8,opt,name=Signature" json:"Signature,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Block) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Block) GetNonce() uint32 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Block) GetPrevious() []byte {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *Block) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Block) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *Block) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Block) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type PushReturn struct {
}

func (m *PushReturn) Reset()                    { *m = PushReturn{} }
func (m *PushReturn) String() string            { return proto.CompactTextString(m) }
func (*PushReturn) ProtoMessage()               {}
func (*PushReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*Info)(nil), "Info")
	proto.RegisterType((*StatusParams)(nil), "StatusParams")
	proto.RegisterType((*SyncParams)(nil), "SyncParams")
	proto.RegisterType((*Block)(nil), "Block")
	proto.RegisterType((*PushReturn)(nil), "PushReturn")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DistributionService service

type DistributionServiceClient interface {
	GetInfo(ctx context.Context, in *Info, opts ...grpc.CallOption) (*Info, error)
	Synchronize(ctx context.Context, in *SyncParams, opts ...grpc.CallOption) (DistributionService_SynchronizeClient, error)
	AddBlock(ctx context.Context, in *Block, opts ...grpc.CallOption) (*PushReturn, error)
}

type distributionServiceClient struct {
	cc *grpc.ClientConn
}

func NewDistributionServiceClient(cc *grpc.ClientConn) DistributionServiceClient {
	return &distributionServiceClient{cc}
}

func (c *distributionServiceClient) GetInfo(ctx context.Context, in *Info, opts ...grpc.CallOption) (*Info, error) {
	out := new(Info)
	err := grpc.Invoke(ctx, "/DistributionService/GetInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributionServiceClient) Synchronize(ctx context.Context, in *SyncParams, opts ...grpc.CallOption) (DistributionService_SynchronizeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_DistributionService_serviceDesc.Streams[0], c.cc, "/DistributionService/Synchronize", opts...)
	if err != nil {
		return nil, err
	}
	x := &distributionServiceSynchronizeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DistributionService_SynchronizeClient interface {
	Recv() (*Block, error)
	grpc.ClientStream
}

type distributionServiceSynchronizeClient struct {
	grpc.ClientStream
}

func (x *distributionServiceSynchronizeClient) Recv() (*Block, error) {
	m := new(Block)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *distributionServiceClient) AddBlock(ctx context.Context, in *Block, opts ...grpc.CallOption) (*PushReturn, error) {
	out := new(PushReturn)
	err := grpc.Invoke(ctx, "/DistributionService/AddBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DistributionService service

type DistributionServiceServer interface {
	GetInfo(context.Context, *Info) (*Info, error)
	Synchronize(*SyncParams, DistributionService_SynchronizeServer) error
	AddBlock(context.Context, *Block) (*PushReturn, error)
}

func RegisterDistributionServiceServer(s *grpc.Server, srv DistributionServiceServer) {
	s.RegisterService(&_DistributionService_serviceDesc, srv)
}

func _DistributionService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Info)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributionServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DistributionService/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributionServiceServer).GetInfo(ctx, req.(*Info))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributionService_Synchronize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DistributionServiceServer).Synchronize(m, &distributionServiceSynchronizeServer{stream})
}

type DistributionService_SynchronizeServer interface {
	Send(*Block) error
	grpc.ServerStream
}

type distributionServiceSynchronizeServer struct {
	grpc.ServerStream
}

func (x *distributionServiceSynchronizeServer) Send(m *Block) error {
	return x.ServerStream.SendMsg(m)
}

func _DistributionService_AddBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Block)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributionServiceServer).AddBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DistributionService/AddBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributionServiceServer).AddBlock(ctx, req.(*Block))
	}
	return interceptor(ctx, in, info, handler)
}

var _DistributionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DistributionService",
	HandlerType: (*DistributionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _DistributionService_GetInfo_Handler,
		},
		{
			MethodName: "AddBlock",
			Handler:    _DistributionService_AddBlock_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Synchronize",
			Handler:       _DistributionService_Synchronize_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "node.proto",
}

func init() { proto.RegisterFile("node.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xd1, 0x8a, 0xd4, 0x30,
	0x14, 0x86, 0x27, 0xee, 0xb4, 0xd3, 0x3d, 0x53, 0x11, 0xa2, 0x48, 0x2c, 0x5e, 0xd4, 0x5c, 0x48,
	0xaf, 0x8a, 0xe8, 0x13, 0xa8, 0x0b, 0xee, 0xe2, 0x20, 0x25, 0x95, 0xbd, 0xcf, 0xb4, 0x67, 0xb7,
	0xc1, 0x35, 0x59, 0x92, 0x74, 0x61, 0xf4, 0x35, 0x7c, 0x11, 0xdf, 0x50, 0x92, 0xb6, 0x33, 0xea,
	0x55, 0xce, 0xf7, 0x73, 0xc8, 0x9f, 0xff, 0x6f, 0x01, 0xb4, 0xe9, 0xb1, 0xbe, 0xb7, 0xc6, 0x1b,
	0xfe, 0x8b, 0xc0, 0xfa, 0x4a, 0xdf, 0x18, 0xca, 0x60, 0x73, 0x8d, 0xd6, 0x29, 0xa3, 0x19, 0x29,
	0x49, 0x75, 0x2e, 0x16, 0xa4, 0xcf, 0x20, 0xb9, 0x96, 0x77, 0xaa, 0x67, 0x8f, 0x4a, 0x52, 0x65,
	0x62, 0x02, 0xfa, 0x1c, 0xd2, 0x1d, 0xea, 0x5b, 0x3f, 0xb0, 0xb3, 0x92, 0x54, 0x6b, 0x31, 0x13,
	0x2d, 0x20, 0xdb, 0x49, 0xe7, 0x2f, 0xa5, 0x1b, 0xd8, 0xba, 0x24, 0x55, 0x2e, 0x8e, 0x4c, 0x2b,
	0x78, 0xb2, 0x53, 0xce, 0xa3, 0xbe, 0xd2, 0x1e, 0xed, 0x8d, 0xec, 0x90, 0x25, 0xd1, 0xeb, 0x7f,
	0x99, 0x73, 0xc8, 0x5b, 0x2f, 0xfd, 0xe8, 0x1a, 0x69, 0xe5, 0x77, 0x47, 0x29, 0xac, 0x2f, 0x8d,
	0xf3, 0xf3, 0xd3, 0xe2, 0xcc, 0x2b, 0x80, 0xf6, 0xa0, 0xbb, 0x79, 0xe3, 0x6f, 0x5f, 0xf2, 0xaf,
	0x2f, 0xff, 0x4d, 0x20, 0xf9, 0x70, 0x67, 0xba, 0x6f, 0x21, 0xe5, 0x47, 0xa3, 0x3d, 0xea, 0xe5,
	0xaa, 0x05, 0x43, 0xca, 0x2f, 0x46, 0x77, 0x18, 0x53, 0x3e, 0x16, 0x13, 0x84, 0x5b, 0x1b, 0x8b,
	0x0f, 0xca, 0x8c, 0x2e, 0xe6, 0xcc, 0xc5, 0x91, 0xc3, 0x9b, 0xbe, 0x1e, 0xee, 0x97, 0x08, 0x71,
	0x0e, 0xad, 0x34, 0xe3, 0xfe, 0x33, 0x1e, 0x58, 0x1a, 0xd5, 0x99, 0xc2, 0xee, 0x85, 0xf4, 0xc8,
	0x36, 0x25, 0xa9, 0xce, 0x44, 0x9c, 0xe9, 0x4b, 0x38, 0x6f, 0xd5, 0xad, 0x96, 0x7e, 0xb4, 0xc8,
	0xb2, 0xb8, 0x7e, 0x12, 0x78, 0x0e, 0xd0, 0x8c, 0x6e, 0x10, 0xe8, 0x47, 0xab, 0xdf, 0xfe, 0x84,
	0xa7, 0x17, 0xca, 0x79, 0xab, 0xf6, 0xa3, 0x57, 0x46, 0xb7, 0x68, 0x1f, 0x54, 0x87, 0xf4, 0x05,
	0x6c, 0x3e, 0xa1, 0x8f, 0xdf, 0x2f, 0xa9, 0xc3, 0x51, 0x4c, 0x07, 0x5f, 0xd1, 0xd7, 0xb0, 0x0d,
	0xed, 0x0c, 0xd6, 0x68, 0xf5, 0x03, 0xe9, 0xb6, 0x3e, 0x75, 0x55, 0xa4, 0x75, 0x6c, 0x83, 0xaf,
	0xde, 0x10, 0xfa, 0x0a, 0xb2, 0xf7, 0x7d, 0x3f, 0xb5, 0x33, 0xeb, 0xc5, 0xb6, 0x3e, 0x59, 0xf3,
	0xd5, 0x3e, 0x8d, 0xbf, 0xca, 0xbb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xf3, 0xb1, 0x1e,
	0x38, 0x02, 0x00, 0x00,
}
